### ISSUE TITLE
Different triggers for each search query

### ISSUE THREAD

**Issue by AstudilloMarillo** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#1]
This is a copy-paste of [madsholme](https://github.com/madsholme)'s request you asked to make an issue for on this repository:

> "i would like to do triggers for each search query so i could do
> 
> con for a confluence search
> j for a jira search
> 
> and then define earch search url and query for each of those."

This would make it similar to how Web Searches on Flow Launcher work, and it would be an amazing feature.

**Comment by Daydreamer-riri** [comment]
Hi @AstudilloMarillo , in the latest version, you can achieve the effect by setting `Keyword` in config file. 

If you don't want to enter a trigger word, you can enable 'Include in global result' in the settings.

<img width="553" alt="image" src="https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/072d4001-8b14-4b8f-93ac-f11153fd2343">

<img width="514" alt="image" src="https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/16211739-ecb0-4a7a-92d3-12c049a34ec0">

If you have any questions or suggestions, please let me know.

**Comment by AstudilloMarillo** [comment]
Thanks, it works great! Because of your plugin, PowerToys Run is now almost complete enough to replace Flow Launcher for me.

One suggestion; Have a 'Name' entry that is separate from the Keyword. That way you could do something like this:

  "w": {
    "Url": "https://en.wikipedia.org/wiki/%s",
    "Name": "Wikipedia"
  }

In the Run window it could show the name 'Wikipedia' in the title instead of just 'w' and still have the subtitle show 'Search using w'. Now you'd have a convenient short keyword but also a descriptive obvious name.

Right now, we're stuck with this:
![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/136191659/af59b439-cb24-45f8-914d-29e5406da230)

**Comment by Daydreamer-riri** [comment]
There now exists a field called "Keyword".

![config-file~2.png](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/f61589af-8a8c-4de0-9ab1-e4b8e46b359c)

For your example, you can configure it like this:

```json
"Wikipedia": {
  "Url": "https://en.wikipedia.org/wiki/%s",
  "Keyword": "w"
}
```

**Comment by AstudilloMarillo** [comment]
> There now exists a field called "Keyword".

Awesome, works great!

**Comment by programcsharp** [comment]
I think I have this set up for the global search (without the ?? prefix) but I can't seem to get it working.

I have WebSearchShortcutStorage.json with keywords like:

```
{
  "Google": {
    "Url": "https://www.google.com/search?q=%s",
    "SuggestionProvider": "Google",
    "Domain": "https://www.google.com"
  },
  "Bing": {
    "Url": "https://www.bing.com/search?q=%s",
    "SuggestionProvider": "Bing",
    "Domain": "https://www.bing.com"
  },
  "GitHub": {
    "Keyword": "gh",
    "Url": "https://www.github.com/search?q=%s",
    "Domain": "https://www.github.com"
  },
  "Wikipedia": {
    "Url": "https://en.wikipedia.org/wiki/%s",
    "Keyword": "w"
  }
}
```
 
and "Include in global result" enabled:

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/994270/e76d4b02-a6ad-424c-beee-e5eec47055a3)

But when I search gh or w prefixes, it fizzles:

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/994270/b2dd380e-4ab8-4c8a-adc8-efcfd642e027)

Of course, with the `??` prefix it works:

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/994270/3fb2e569-d1d2-4c52-aa3b-10a074394c6b)

What am I missing?

**Comment by Daydreamer-riri** [comment]
Hi @programcsharp , not "WebSearch, "but "WebSearchShortcut".

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/167b8bb7-efa0-46e9-aecc-be62fb269afe)

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/e3ebf9d7-6b28-410a-b25d-b7867a496b13)

**Comment by programcsharp** [comment]
🤣 🤣 thanks, that would be why. Works fantastic now, thanks for all of the work you've done here!
