### ISSUE TITLE
On a new machine, can't get it to recognize my searches

### ISSUE THREAD

**Issue by mbaas2** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#12]
I have a new laptop and I#ve chosen to set everything up from scratch. Unfortunately, WSS gives me problems as it doesn't list any of my searches.
The list of my searches (admittedly I have remove a few intranet-only searches):
````
{
  "Google": {
    "Url": ["https://www.google.com/search?q=%s","https://www.bing.com/search?q=%s"],
    "Domain": "https://www.google.com"
  },
  "Bing": {
    "Url": "https://www.bing.com/search?q=%s",
    "Domain": "https://www.bing.com"
  },
  "GitHub": {
    "Url": "https://www.github.com/search?q=%s",
    "Domain": "https://www.github.com"
  },
  "APLCart": {
    "Url": "https://aplcart.info?q=%s",
    "Comain": "https://aplcart.info"
  },
  "dict.cc": {
    "Url": "https://www.dict.cc/?s=%s",
    "Domain": "https://www.dict.cc"
  },
  "FontAwesome": {
    "Url": "https://fontawesome.com/search?0=r&q=%s",
    "Domain": "https://fontawesome.com"
  },
  "Unicode": {
    "Url": "https://unicode-table.com/de/search/?q=%s",
    "Domain": "https://unicode-table.com"
  },
  "MimeKit": {
    "Url": "https://mimekit.net/docs/search.html?SearchText=%s",
    "Domain": "https://mimekit.net"
  }
}
````
And now, heree's a bing search;
![grafik](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/5645494/9722c3cb-29a0-415d-a25c-48fc5442347d)

The standard websearch is disabled.

Also, when entering "??!config", the choice "Open Config File" only pops up after entering the last letter. Are the "system commands" not included in autocomplete suggestions?

**Comment by Daydreamer-riri** [comment]
Sorry I can't use my computer in the weekends. I can only give you my guess. Can you try to remove the "Domain" field?

**Comment by mbaas2** [comment]
That doesn't help, sorry. Enjoy your weekend! (no hurry)

**Comment by Daydreamer-riri** [comment]
Hi @mbaas2 , I would like to know if the default configuration shortcuts can be correctly displayed when you newly install WSS (without any configuration yet).

**Comment by mbaas2** [comment]
I removed the old config file and the the plugin folder, installed again: all is fine! Then I pasted in my previous searches and reloaded the config: now it only shows the initial list of searches when I start typing (and my searches are not shown). Could there be a cache that I failed to delete? (I did !reload several times)
That sounds as if it had a problem loading my searches - but the json itself is fine (it validates). Also I'm using just the regular  letters for names, no national chars and only "_" as a separator, so I don't think they could cause problems.

**Comment by Daydreamer-riri** [comment]
![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/24e41410-05cc-4dfd-9890-2c25fd4cc265)
After I removed it, everything returned to normal.

**Comment by mbaas2** [comment]
Duh...I'm so blind! I lef that experiment in there🥵
Sorry for the trouble - and thanks for your patience!  (Maybe some error handling during `!reload` would help, though)

**Comment by Daydreamer-riri** [comment]
Indeed. I should show some hint when parsing fails.

**Comment by Daydreamer-riri** [comment]
By the way, I noticed that you haven't set up search suggestions in your configuration. Have you tried it? I'm concerned that early users might not be aware of this new feature.

**Comment by mbaas2** [comment]
Thanks! I had seen it mentioned and tried it, but somehow didn't get suggestions.:
![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/5645494/4eeb2f8f-99c3-4d19-af09-ab5a933f6dfd)

**Comment by mbaas2** [comment]
Ok, it's rather embarrassing (but probably not surprising😉) - but I had another fault in my config, so that setting had no effect!
(Is there any way you could allow JSON5 in config files?  That would not bark on extraneous "," and also doesn't need quoted fieldnames etc.

**Comment by Daydreamer-riri** [comment]
I am not a skilled C#developer, I am not sure whether it has built -in support for JSON5. However, I will show some errors at the Search results if there are errors, hoping that this can provide some help.

**Comment by mbaas2** [comment]
Thanks - that will surely help a lot!👍
