### ISSUE TITLE
Can I change the Icon of the websites?

### ISSUE THREAD

**Issue by yuvalg72** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#13]
I tried to change 3 of the icons of the websites I added but when I done a reload, it just overrided the icons that I replaced.

I tried to edit the code, like this, but nothing:

    "CRM-Search-by-Case-Number": {
    "Url": "https://gitpro.crm4.dynamics.com/support",
    "Domain": "https://gitpro.crm4.dynamics.com/support",
    "Keyword": "CRM",
    "Logo": "https://i.imgur.com/LS21NHV.png",
  },
  
  *******
    
    "CRM-Search-by-Case-Number": {
    "Url": "https://gitpro.crm4.dynamics.com/support",
    "Domain": "https://gitpro.crm4.dynamics.com/support",
    "Keyword": "CRM",
    "Icon": "https://i.imgur.com/LS21NHV.png",
  },
  
  
  Thank you in advance.

**Comment by mbaas2** [comment]
I just wanted to create an issue about "Domain" when I saw this discussion!😉
What's confusing about the doc is that samples use `Domain`, but it's not documented. 

I don't know if that was my own silly attempt to make sense of it or if I saw it mentioned somewhere, but I had assumed it would be used to load a favicon.

**Comment by Daydreamer-riri** [comment]
> I just wanted to create an issue about "Domain" when I saw this discussion!😉
> What's confusing about the doc is that samples use `Domain`, but it's not documented. 
> 
> I don't know if that was my own silly attempt to make sense of it or if I saw it mentioned somewhere, but I had assumed it would be used to load a favicon.

Maybe I mistakenly output it to the initialization configuration file when initializing. Will fix it in the next version.

**Comment by yuvalg72** [comment]
> Custom icons are not considered in the plugin's current implementation. Is the icon of the website you set not loading?
> 

The icon of the website is loading, but three of the websites I added to the plugin are hosted on Azure, and they display the default Microsoft icon. I want to customize it so that each website will have its own icon in the plugin.

Is there any workaround or manual adjustment I can make to set the icons myself? This would be the ideal solution for me until the option to customize icons is added in future versions.

Thank you for your attention to this matter. Looking forward to your guidance. :)

**Comment by mbaas2** [comment]
Agreed - I would find that very useful, too :)

**Comment by Daydreamer-riri** [comment]
The current version may not be able to do this (unless there is some BUG). This requirement seems reasonable, and I can support it in the next version.

**Comment by Daydreamer-riri** [comment]
Hi @yuvalg72 , now you can now set custom icons in the latest version.

See: https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut?tab=readme-ov-file#iconurl

**Comment by yuvalg72** [comment]
> Hi @yuvalg72 , now you can now set custom icons in the latest version.
> 
> See: https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut?tab=readme-ov-file#iconurl


Hey @Daydreamer-riri , I'm so sorry for the late response, you published the version with the custom icons so fast but I had some troubles in my own life. :(
I tried to change the Icon, but seems it still not working.
 
A sample of the code is attached:

  "CRM-Search-by-Case-Number": {
    "Url": "https://yuvalcrm.dynamics.com/main.aspx?appid=1164454b-f273-ee11-8179-0022489fda83&forceUCI=1&pagetype=search&searchText=%s&searchType=0",
    "Keyword": "CRM",
    "IconUrl": "https://convertico.com/images/1715163536.0751/logo-dynamics365.ico"
  },


Even if I trying to do it with the "Domain" field:, still don't work:
  "CRM-Search-by-Case-Number": {
    "Url": "https://yuvalcrm.dynamics.com/main.aspx?appid=1164454b-f273-ee11-8179-0022489fda83&forceUCI=1&pagetype=search&searchText=%s&searchType=0",
    "Keyword": "CRM",
    "Domain": "https://yuvalcrm.crm4.dynamics.com/main.aspx/",
     "IconUrl": "https://convertico.com/images/1715163536.0751/logo-dynamics365.ico"
  },


Best Regards bro and thank you again :)

**Comment by Daydreamer-riri** [comment]
![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/8021b57b-e4c7-4014-baf4-42943cc215cf)

The configuration I'm using seems to work normally in the latest version. Have you updated to the latest version? Or is the format of the configuration file correct?

Additionally, I hope everything in your life is going well!

**Comment by yuvalg72** [comment]
Well, seems to be working well now. Thank you, maybe the restart helped or something else.
