### ISSUE TITLE
[Bug] Sometimes, not all characters are sent

### ISSUE THREAD

**Issue by AstudilloMarillo** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#2]
When you finish your query and immediately press enter to send, the last 1 or 2 characters have a chance of not being sent. They are however registered in the input field.

**Comment by Daydreamer-riri** [comment]
This may be related to the "smooth input" in the settings. You can disable it to see if the problem improves. 

The plugin only provides "action", and the input it receives is provided by the launcher(powertoys-run) itself. So this should be the strategy of the launcher itself.

**Comment by AstudilloMarillo** [comment]
> This may be related to the `Input Smoothing` in the settings. You can disable it to see if the problem improves.

I will give this a try, thank you!

> The plugin only provides "action", and the input it receives is provided by the launcher(powertoys-run) itself. So this should be the strategy of the launcher itself.

This makes sense. If I keep experiencing this issue, I'll raise it with the launcher.
