### ISSUE TITLE
feature request: type keyword + tab to select site to search

### ISSUE THREAD

**Issue by bradyab** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#22]
love this plugin! one of my favorite features from raycast

it would be even better if it mimicked chrome's omnibar UX and allowed you to select the site to search with e.g. "chatgpt <tab> <query>" instead of "?? chatgpt <query>"

not sure if this conflicts with powertoys run's global keywords, but saving a few extra keystrokes every time i use this extension would be great.

**Comment by Daydreamer-riri** [comment]
Hi @bradyab , thank you for your love!

I think this reply can help you: https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/issues/1#issuecomment-2014895380

**Comment by bradyab** [comment]
amazing, works perfectly!

**Comment by areographe** [comment]
> Hi @bradyab , thank you for your love!
> 
> I think this reply can help you: [#1 (comment)](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/issues/1#issuecomment-2014895380)

hi, this link doesn't work, but i have the same question

**Comment by Daydreamer-riri** [comment]
Hi @areographe, you can juse enable this option.
![image](https://github.com/user-attachments/assets/735f9bb0-c991-42ca-b3c4-7390634cd235)

**Comment by areographe** [comment]
> Hi @areographe, you can juse enable this option. ![image](https://private-user-images.githubusercontent.com/70067449/365093380-735f9bb0-c991-42ca-b3c4-7390634cd235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTAxODEsIm5iZiI6MTcyNTg0OTg4MSwicGF0aCI6Ii83MDA2NzQ0OS8zNjUwOTMzODAtNzM1ZjliYjAtYzk5MS00MmNhLWIzYzQtNzM5MDYzNGNkMjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OGI0MWJlYmJiNjQ5NmMzYWQzZGEzZjdmMDc3OGFkYWFmODk3NjI2NzVmODI1NTczYTExY2JiNGE4ZGZhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KI5qoBOAFkXxxZ3zkkxSa1egbMOuxyu4PHLs-XnaJYk)

great, thank you!
