### ISSUE TITLE
failed to initialize plugin

### ISSUE THREAD

**Issue by SVNKoch** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#28]
I used [PTR](https://github.com/8LWXpg/ptr/) to install your plugin.
I have the normal default websearch plugin enabled
When I open the query window the first time after starting up power toys, it pops up an error dialog, that this plugin couldn't be initialized.
Afterwards no special searchr esults show up when using the ?? key

Sadly I didn't find any logs that could be useful.

**Comment by Daydreamer-riri** [comment]
Thanks for your report, I will try to reproduce this problem with ptr. By the way, what is your powertoys version? And can you initialize it normally using the method in README?

**Comment by SVNKoch** [comment]
I think PTR does the same.
I uninstalled your plugin and installed it manually. The problem still persists.
I'm using v85.1

**Comment by Daydreamer-riri** [comment]
Please upgrade to the latest powertoys and try again. The latest version of web search shortcut uses 0.86.0 of the powertoys SDK dependency.

**Comment by SVNKoch** [comment]
yep just tried that, and now it works. Sorry and thanks 💙

**Comment by Daydreamer-riri** [comment]
It looks like the minimum version in my documentation requires updates. I will update as soon as possible.
