### ISSUE TITLE
?? Reload does not work

### ISSUE THREAD

**Issue by mbaas2** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#3]
Entering `?? Reload` does not give me the choice of `Reload` as shown in the instructions.
![grafik](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/5645494/fce98ac1-de65-4de9-9d33-015ca53044c2)

(...and executing it does not Reload)

According to `plugin.json`, I am using Version 1.0.0, whereas the release page showed 0.1.1

**Comment by Daydreamer-riri** [comment]
Thanks for pointing this out! Currently only the "reload"(not Reload) keyword works. This problem will be fixed in the next version.

**Comment by Daydreamer-riri** [comment]
Hi @mbaas2 , this issue has been resolved in v0.1.2, please try to update the new version.

**Comment by mbaas2** [comment]
Thanks - that was impressively quick! 👍
Unfortunately I don't see a change in behavior after installing & reloading PT!

**Comment by Daydreamer-riri** [comment]
<img width="534" alt="image" src="https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/08eb49fa-cd10-4df4-85a9-045a776be9e0">

Are you still unable to see this option?

**Comment by mbaas2** [comment]
Oh - with the exclamation mark I do see it! The instructions did not show that!

**Comment by Daydreamer-riri** [comment]
> Thanks - that was impressively quick! 👍 Unfortunately I don't see a change in behavior after installing & reloading PT!

Sorry, I found the screenshot in the document misleading. `Reload` is what the launcher itself replaces with my input.  To trigger this option, you need to type '!reload`.
