### ISSUE TITLE
How to select a search engine? 

### ISSUE THREAD

**Issue by mbaas2** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#4]
This might be a lack of doc - or a missing feature, I'm not sure.
Let's say I have a search "abcdefghijk" (long search names are useful to describe details etc.) - how can I search with that engine once it's shown in the menu (maybe after I typed "abc")?   (Ctrl+Enter immediately goes to the URL - but I've not yet had a chance to enter the search term...)
Having to enter the full name "abcdefghijk" can't be the only way!?

**Comment by Daydreamer-riri** [comment]
Just press Enter😂

If I haven't made myself clear, or if you have any questions, let me know and I'll get back to you as soon as possible.

**Comment by Daydreamer-riri** [comment]
I should put a video or GIF in the doc later to help users understand the usage.

**Comment by Daydreamer-riri** [comment]
Hi, @mbaas2 , I'll close this issue for now.  If there's still any questions, we can reopen it.

**Comment by mbaas2** [comment]
Sure, that's fine. <Enter> was too obvious ;)  I feared it would trigger something, so the thought did not even occur to me :((
