### ISSUE TITLE
WSS has wrong description in PT Run's list of plugins

### ISSUE THREAD

**Issue by mbaas2** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#5]
![grafik](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/5645494/e35cc524-adc0-42c6-a7e5-508867e76e90)

**Comment by Daydreamer-riri** [comment]
Wow, I forgot it.  This is the description of the project template.
