### ISSUE TITLE
Default shortcut option

### ISSUE THREAD

**Issue by nortakales** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#6]
I'd like the ability to search using a default shortcut if I do not type any of the keywords. This is because I'll use my primary search shortcut most of the time, and occasionally I'd like to use a keyword to select a different shortcut.

For example, in the config I could do something like this:

```json
{
  "Google": {
    "Url": "https://www.google.com/search?q=%s",
    "SuggestionProvider": "Google",
    "Keyword": "g"
    "Default": true
  },
  "Bing": {
    "Url": "https://www.bing.com/search?q=%s",
    "SuggestionProvider": "Bing",
    "Keyword": "b"
  },
  "GitHub": {
    "Url": "https://www.github.com/search?q=%s",
    "Keyword": "gh"
  }
}
```

Then, typing just `?? test` should be equivalent to typing `?? g test`.

You'd have to decide what happens if multiple shortcuts have `"Default": true` though.. I guess just the first should win?

Also, thank you so much for building this. It is mind boggling to me that this isn't built into PowerToys. Perhaps now that you have created this they will merge it into PowerToys.

**Comment by Daydreamer-riri** [comment]
Hi @nortakales , Thanks for your issue. At the time of creation, I wanted to use this plugin in conjunction with the `WebSearch` plugin. That's why I set the default trigger to `??`. 

I thought at the time that WebSearch could provide an option for a "default search engine". But now I also think that using two plugins at the same time may increase the cognitive load for users. And, `WebSearch` does not provide the search suggestion feature.

I can do the 'default' feature, but I'm not sure whether it should be enabled by default (put it into the initial configuration file), what do you think?

**Comment by nortakales** [comment]
It's probably not necessary in the initial configuration file as long as it is documented in the readme. This would also force users to read that only one default should be set.

You could also get around that issue (multiple defaults being set by the user) if you changed the JSON structure of the config file such that you could do something like: 

```
{
    "Shortcuts": {
        "Google": {
            "Url": "https://www.google.com/search?q=%s",
            "SuggestionProvider": "Google",
            "Keyword": "g"
        },
        "Bing": {
            "Url": "https://www.bing.com/search?q=%s",
            "SuggestionProvider": "Bing",
            "Keyword": "b"
        },
        "GitHub": {
            "Url": "https://www.github.com/search?q=%s",
            "Keyword": "gh"
        }
    },
    "Default": "Google"
}
```

**Comment by Daydreamer-riri** [comment]
> It's probably not necessary in the initial configuration file as long as it is documented in the readme. This would also force users to read that only one default should be set.

Sure. This feature can be included in v0.3.0.

About config,I want the JSON structure of the configuration file to be as simple as possible.  So I prefer the first.
I think "the first should win" is intuitive and not confusing to users.

Hopefully, there will be a better, visual way to configure in the future🤔.

**Comment by Daydreamer-riri** [comment]
Hi @nortakales , I have a question for your opinion: When displaying suggestions from the default search engine, how should the priority between these suggestions and other search engines be set?

**Comment by nortakales** [comment]
Good question. I'm not sure what most people would think, but to me it would make sense for the search engines to be shown with higher priority. And if you specifically want only the suggestions from your default search engine you can simply type the shortcut for it.

**Comment by Daydreamer-riri** [comment]
Hi @nortakales, this feature has been implemented in the latest version. Give it a try!
