### ISSUE TITLE
Include whitespace at end of query when finding matching search engines

### ISSUE THREAD

**Issue by LilyRose2798** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#7]
It seems that an unintended side-effect of using `RemoveEmptyEntries` in the code [here](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/blob/main/Community.PowerToys.Run.Plugin.WebSearchShortcut/Main.cs#L187) makes it so that when you type a space after a valid search engine name/keyword it still displays other search engines that include the text you typed as a substring.
For example here I have `wa` as a keyword for `WolframAlpha`, and while it works correctly once I start typing a search query:

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/1974590/50509fbd-1e1a-4599-b598-809e9649d552)

If I just have a space after the keyword it still includes other engines:

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/1974590/bb43cae1-d72c-40de-b903-3322fe534569)

Ideally having a space after the search engine name/keyword should be treated as having started a search query that consists of an empty string, filtering out all other results. If you hit enter on it in this state as well it should either substitute %s for an empty string and open the `Url`, or just open the `Domain` instead.

**Comment by Daydreamer-riri** [comment]
This is something I didn't consider. Thanks for pointing this out!

**Comment by Daydreamer-riri** [comment]
Hi @LilyRose2798 , I found I couldn't get the trailing whitespace. Maybe this can't be done in plugins...

![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/f0cbb4e2-c6a3-4d79-86e6-2fbc92342afd)
![image](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/70067449/14bcc0b5-2211-413f-8b41-1471e7cfecc7)

**Comment by LilyRose2798** [comment]
That's a shame. I'll try and do some of my own testing tomorrow to see if there's any way to get it with whitespace. If it can't be done though, I'd say the next best thing would be checking if the input exactly matches a known name/keyword, and if so, treat it as if that search engine is selected (i.e. show it as the only result).
