### ISSUE TITLE
Use keyword shortcut without argument?

### ISSUE THREAD

**Issue by robob27** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#9]
Is it possible to allow a keyword shortcut to be configured so that an argument is not required? For example:

`srmine` -> `https://github.com/SomeRepo/SomeRepo/issues/assigned/robob27`

Currently the only way I can find to accomplish this is to add an argument like `/` i.e. `srmine /`. I know in this case it is not really a search, it is just a bookmark opened via keyword - so maybe I'm trying to use the wrong plugin to accomplish this.. but it would be amazing to manage all of these things in one place.

On Mac I use Alfred Workflows to accomplish a similar thing using their [Open URL action](https://www.alfredapp.com/help/workflows/actions/open-url/) which is why these things feel related to me.

>Using a URL without a {query} will open a fixed website URL. Optionally, including {query} will fill this with the argument you've passed through from the previous object in your workflow (e.g. a search term for Pinterest).

Thanks so much for this plugin. I've been looking for something like this on Windows for a while!

**Comment by robob27** [comment]
@Daydreamer-riri That sounds great. Thanks again!

**Comment by Daydreamer-riri** [comment]
Hi @robob27 , looks like someone beat me to implement this feature! 

I also need to improve the logic of website icon acquisition, and will release the next version as soon as possible.

**Comment by robob27** [comment]
I cloned and built the solution locally as soon as I got the notification 😄. Works great! Thanks for the quick update @Git-snake ❤️.

**Comment by Daydreamer-riri** [comment]
The new version is released!
